version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'api-mysql:/var/lib/mysql'
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
volumes:
  api-mysql:
    driver: local
